# Dummy Comment to trigger github action
module-name: telemetry
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/telemetry-manager:main
  - europe-docker.pkg.dev/kyma-project/prod/tpi/otel-collector:0.94.0-fc04f979
  - europe-docker.pkg.dev/kyma-project/prod/tpi/fluent-bit:2.2.2-b5220c17
  - europe-docker.pkg.dev/kyma-project/prod/directory-size-exporter:v20240123-4f99d571
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
