name: PR Load Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true

env:
  IMG: europe-docker.pkg.dev/kyma-project/dev/telemetry-manager:PR-${{ github.event.inputs.pr_number }}
  K8S_VERSION: "1.27"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  load-test:
    strategy:
      max-parallel: 3
      matrix:
        argument: ["-n test-0 -t traces", "-n test-1 -t traces -m true", "-n test-2 -t traces -b true", "-n test-3 -t metrics", "-n test-4 -t metrics -m true", "-n test-5 -t metrics -b true"]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: 'refs/pull/${{ github.event.inputs.pr_number }}/head'
          repository: ${{ github.repository }}

      - name: Setup Golang
        uses: "./.github/template/setup-golang"

      # Generate the cluster name to be used for cluster creation
      - name: Setup gardener cluster name
        run:  echo "GARDENER_CLUSTER_NAME=$(echo '${{ matrix.argument }}' | awk '{print $2}')" >> $GITHUB_ENV

      # save gardener kubeconfig to a temp file in order to pass it to the command
      - name: Save service account to file
        shell: bash
        run: 'echo "$GARDENER_SA" > /tmp/gardener-sa.yaml'
        env:
          GARDENER_SA: ${{ secrets.GARDENER_SA }}

      # provision cluster and run tests
      - name: Provision Gardener
        run: make provision-gardener
        env:
          GARDENER_SECRET_NAME: ${{ secrets.GARDENER_SECRET_NAME }}
          GARDENER_PROJECT: ${{ secrets.GARDENER_PROJECT }}
          GARDENER_SA_PATH: /tmp/gardener-sa.yaml
          GARDENER_K8S_VERSION: ${{ K8S_VERSION }}

      - name: Deploy Istio Module
        run: hack/deploy-istio.sh

      - name: Deploy Telemetry
        run: hack/deploy-telemetry.sh

      # Run the load test
      - name: Run Load test
        working-directory: docs/contributor/telemetry-load-test
        run: ./assets/run-load-test.sh ${{ matrix.argument }}

      - name: Deprovision Gardener
        run: make deprovision-gardener
